### ISSUE TITLE
运行rsbind . android all后报这个错误，是什么原因？

### ISSUE THREAD

**Issue by hamzsy** [rs-bind/rsbind#22]
ndk是r23b
process '"/opt/Android/ndk-r21/toolchains/llvm/prebuilt/linux-x86_64/bin/arm-linux-androideabi-strip" "-s" "target/armv7-linux-androideabi/release/libmy_project_android_bridge_prj.so"' finished with: exit status: 0
thread 'main' panicked at 'generate failed: Error(NdkBuild(Error(Ndk(UnsupportedTarget), State { next_error: None, backtrace: InternalBacktrace { backtrace: None } })), State { next_error: None, backtrace: InternalBacktrace { backtrace: None } })', rsbind/src/main.rs:68:10
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
谢谢了！

**Comment by rs-bind** [comment]
可以看下你的rsbind.toml是怎么配置的吗？

**Comment by rs-bind** [comment]
应该是有些target已经被官方废弃了，我删掉就好了。稍等我发一个PR。

**Comment by hamzsy** [comment]
> 可以看下你的rsbind.toml是怎么配置的吗？

没加rsbind.toml，直接运行的rsbind . android all

**Comment by rs-bind** [comment]
我在创建PR，要想先快速解决问题的话，你可以先拷贝demo的rsbind.toml放到你的工程。

**Comment by rs-bind** [comment]
已经合入。
